"""Add fields

Revision ID: 0ffe86ab0cc7
Revises: 
Create Date: 2021-12-13 01:44:21.280977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ffe86ab0cc7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sank_merch_care_instructions', table_name='sank_merch')
    op.drop_column('sank_merch', 'care_instructions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sank_merch', sa.Column('care_instructions', sa.VARCHAR(length=512), nullable=True))
    op.create_index('ix_sank_merch_care_instructions', 'sank_merch', ['care_instructions'], unique=False)
    # ### end Alembic commands ###
