"""empty message

Revision ID: 7bf8119b81c5
Revises: e2f66b3b1ca8
Create Date: 2022-01-09 19:43:39.332381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bf8119b81c5'
down_revision = 'e2f66b3b1ca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variation', sa.Column('price', sa.Float(), nullable=True))
    op.create_index(op.f('ix_variation_price'), 'variation', ['price'], unique=False)
    op.create_index(op.f('ix_variation_product_id'), 'variation', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_variation_product_id'), table_name='variation')
    op.drop_index(op.f('ix_variation_price'), table_name='variation')
    op.drop_column('variation', 'price')
    # ### end Alembic commands ###
