"""Add measurements to size.

Revision ID: e2f66b3b1ca8
Revises: c281757598ea
Create Date: 2021-12-13 01:54:20.484989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2f66b3b1ca8'
down_revision = 'c281757598ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('size', sa.Column('measurement', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_size_measurement'), 'size', ['measurement'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_size_measurement'), table_name='size')
    op.drop_column('size', 'measurement')
    # ### end Alembic commands ###
